project_id = "meertwtenhlmnlpwxhyz"

[functions.realtime-voice-relay]
verify_jwt = false

[functions.realtime-token-simple]
verify_jwt = false

[functions.realtime-token-enhanced]
verify_jwt = false

[functions.assessment-generator]
verify_jwt = false

[functions.process-pdf]
verify_jwt = false

[functions.pdf-text-extractor]
verify_jwt = false

[functions.pdf-image-extractor]
verify_jwt = false

[functions.text-image-correlator]
verify_jwt = false

[functions.language-detector]
verify_jwt = false

[functions.batch-processor]
verify_jwt = false

[functions.fetch-pexels-image]
verify_jwt = false

[functions.list-pdf-content]
verify_jwt = false

[functions.generate-assessment]
verify_jwt = true

[functions.get-assessment]
verify_jwt = true

[functions.update-assessment]
verify_jwt = true

[functions.get-pdf-images]
verify_jwt = false

[functions.search-pexels]
verify_jwt = false

[functions.upload-image]
verify_jwt = true

[functions.duplicate-assessment]
verify_jwt = true