# Supabase Edge Functions Configuration
# Place this in your project root or .supabase/functions directory

[functions.pdf-upload]
verify_jwt = true
import_map = "./import_map.json"

[functions.pdf-processor]
verify_jwt = false  # Internal function, called by other functions
import_map = "./import_map.json"

[functions.text-extractor]
verify_jwt = false  # Internal function
import_map = "./import_map.json"

[functions.image-extractor]
verify_jwt = false  # Internal function
import_map = "./import_map.json"

[functions.language-detector]
verify_jwt = false  # Internal function
import_map = "./import_map.json"

[functions.content-correlator]
verify_jwt = false  # Internal function
import_map = "./import_map.json"

[functions.quality-validator]
verify_jwt = false  # Internal function
import_map = "./import_map.json"

[functions.assessment-generator]
verify_jwt = false  # Internal function
import_map = "./import_map.json"
